services:
  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  #消息队列
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq # 持久化数据
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 111111

  meilisearch:
    image: getmeili/meilisearch:v1.13
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=jsMYzrk7POQWvVZKhg5c_DjjiNeUxsrsq_adLxtVTzQ
    ports:
      - "7700:7700"
    volumes:
      - ./data/meili_data:/meili_data